# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kTgt4ttOoLaOSBkbd64MoGtnXU8OsyU_
"""

!pip install nfstream
import nfstream
from nfstream import *
import csv
import pandas as pd 

# Open the pcap file
streamer = NFStreamer(source='./50_sec_ddos.pcap')

df = streamer.to_pandas(columns_to_anonymize=[])
#print(df)

for i in range(len(df)):
    print(df.iloc[i:])

df.to_csv('./ddos.csv')